### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by femtotrader**
I prefer to submit a PR instead of committing directly here.

This is just a very basic version with JTS to Datashape but no Datashape to JTS

### CODE REVIEW

**Comment by femtotrader** [comment]
@pwalsh feel free to comment here

**Comment by pwalsh** [comment]
@femtotrader looks like a good start. I don't have time to dive into DataShape and do a proper review of the code now, but I'm very excited by the idea and by [odo](http://odo.readthedocs.org/en/latest/index.html) in general :). 

I'm more than happy to have you run on this (and merge this PR) and get the basic functionality down.

We can then do a review, package it up, and also make some announcements out to the OKFN Labs network, and find out how many other people are using odo/DataShape.

cc @danfowler @rgrp

**Comment by femtotrader** [comment]
For now there is only JTS -> DataShape no DataShape -> JTS support but I think that's enough to provide a support for `odo` when a datapackage is a source (not a destination).
Some improvements need to be done in `trickvi/datapackage` (why is not part of `okfn`?) to export data from DataPackages with several resources. https://github.com/trickvi/datapackage/issues/45

I also think that we should test this `odo` support with several DataPackages (all https://github.com/datasets/registry ) so we need to have a script to download them all (this is also related to add cache support to `trickvi/datapackage` https://github.com/trickvi/datapackage/issues/61

**Comment by rufuspollock** [comment]
@femtotrader do you want to go ahead and merge - or i'm happy to for you whilst @pwalsh is away.

**Comment by femtotrader** [comment]
I don't see merge button in GitHub so I think I'm not allowed to.

I did a fork of repo and I worked on my own repo. I prefer an other dev have a look and merge PR if you don't mind.

**Comment by rufuspollock** [comment]
@femtotrader ok - merging now. We will try to get a team sorted and +1 on review and merge model :-)

**Pull request merged**
